sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
matrix:
  include:
    - node_js: "8"
    - node_js: "6"
    - node_js: "4"
script:
  - npm run lint
  - npm test
before_script:
  - npm prune
jobs:
  include:
    - stage: npm release
      node_js: "8"
      script: skip
      after_success:
        - npx semantic-release
branches:
  only:
    - master
