version: 2.1

orbs:
  prodsec: snyk/prodsec-orb@1
  
commands:
  install:
    steps:
      - run:
          name: Install
          command: npm install

jobs:
  security-scans:
    resource_class: small
    docker:
      - image: cimg/node:lts
    steps:
      - checkout
      - install
      - prodsec/security_scans:
          mode: auto

workflows:
  CICD:
    jobs:
      - prodsec/secrets-scan:
          name: scan repository for secrets
          context:
            - snyk-bot-slack
          channel: cli-alerts

      - security-scans:
          context: devex_cli
